# Generated by Django 5.1.2 on 2024-10-12 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "current_project",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("workload_level", models.IntegerField(default=0)),
                ("previous_workload_level", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkloadData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("workload_level", models.IntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workload.employee",
                    ),
                ),
            ],
        ),
    ]
