# Generated by Django 4.2.17 on 2024-12-12 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_feature_resource", "Can feature resource"),
                    ("can_publish_resource", "Can publish resource"),
                ],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("ALL", "All Employees"),
                    ("MANAGER", "Managers Only"),
                    ("HR", "HR Only"),
                    ("ADMIN", "Administrators Only"),
                ],
                default="ALL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resource", name="content", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT", "Document"),
                    ("VIDEO", "Video"),
                    ("LINK", "External Link"),
                    ("ARTICLE", "Article"),
                ],
                default="DOCUMENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="resource",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="resources/"),
        ),
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="support.resourcecategory",
            ),
        ),
        migrations.CreateModel(
            name="ResourceRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="support.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("resource", "user")},
            },
        ),
    ]
