# Generated by Django 4.2.17 on 2024-12-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_resourcecategory_alter_resource_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidelineDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="guidelines/")),
                ("workload_levels", models.CharField(default="[]", max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "vector_store_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="chatmessage", name="is_ai_response",),
        migrations.AddField(
            model_name="chatmessage",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="workload_level",
            field=models.IntegerField(null=True),
        ),
    ]
