# Generated by Django 4.2.17 on 2024-12-15 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "support",
            "0004_guidelinedocument_remove_chatmessage_is_ai_response_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportActionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=100)),
                ("current_workload_level", models.IntegerField()),
                ("previous_workload_level", models.IntegerField()),
                ("immediate_action", models.TextField()),
                ("long_term_strategy", models.TextField()),
                ("resources", models.TextField()),
                ("priority_level", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Support Action Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
