# Generated by Django 4.2.17 on 2024-12-15 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_delete_department_delete_employeemetrics"),
    ]

    operations = [
        migrations.AlterModelOptions(name="employee", options={},),
        migrations.AddField(
            model_name="employee",
            name="last_workload_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_workload_level",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="previous_workload_level",
            field=models.IntegerField(default=3),
        ),
    ]
